spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt:
    secret-key: superdupersecuredkeyforthisawesomeapplication
    token-prefix: 'Bearer '
    token-expiration-after-days: 1